services:
  noray:
    image: ghcr.io/foxssake/noray:main
    container_name: noray-server
    restart: unless-stopped
    ports:
      - "8890:8890"     # TCP port for client connections
      - "8891:8891"     # HTTP port for metrics
      - "8809:8809/udp" # UDP port for remote registration
      - "49152-51200:49152-51200/udp" # UDP relay ports
    # Binding many ports can take time
    # Use host networking locally
    network_mode: host
    env_file:
      - .env
